# Generated by Django 6.0.4 on 2026-04-20 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=300)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('website', models.URLField(blank=True)),
                ('service', models.CharField(choices=[('seo_content', 'SEO Content Writing'), ('seo_services', 'SEO Services'), ('translation', 'Translation'), ('editing', 'Editing'), ('link_building', 'Link Building'), ('other', 'Other / Multiple')], max_length=50)),
                ('industry', models.CharField(choices=[('igaming', 'iGaming'), ('fintech', 'Fintech'), ('crypto', 'Crypto'), ('other', 'Other')], max_length=50)),
                ('volume', models.CharField(blank=True, choices=[('small', 'Small (1–5 pieces)'), ('medium', 'Medium (6–20 pieces)'), ('large', 'Large (20+ pieces)'), ('ongoing', 'Ongoing retainer')], max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
